services:
  server:
    build: ./shopping-list-api
    image: shopping-list-api
    container_name: shopping-list-api
    ports:
      - "5000:5000"
    env_file: ./shopping-list-api/.env
  client:
    build: ./shopping-list-react
    image: shopping-list-react
    container_name: shopping-list-react
    depends_on:
      - server
    ports:
      - "3000:3000"